### ISSUE TITLE
aapt2.exe not working with --output-to-dir

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [infinitespace-studios/XamarinLegacyDynamicAssetsExample#3]
Hi! I get an error when running aapt2.exe. It says:

error: failed to write assets/Foo.txt to archive: The system cannot find the file specified. (2).

This appears because of using --output-to-dir command line parameter. How did you get this working?

_(I've confirmed that this is not working even with the latest aapt2.exe downloaded from Google Maven.)_

_(I am on Windows 11, if that matters.)_

_(It works on Linux, though.)_

I got everything working using aapt2 on WSL and then importing the resulting zip file to the project using the following:
  ```
  <ItemGroup>
    <AndroidAppBundleModules Include="C:\assetpack\assets.zip" />
  </ItemGroup>
  ```
This is a manual solution though.

**Comment by dellis1972** [comment]
ok, so the windows aapt2 doesn't support this. I'll revert to the old code when I get back from Holidays.

**Comment by dellis1972** [comment]
I reverted the code which uses the `--output-to-dir ` flag to the original version which creates a zip and then extracts the data. 
We can re-enable the new flag once it makes it into the windows version of aapt2.
