### ISSUE TITLE
Install-time asset packs can be included in the project easier

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [infinitespace-studios/XamarinLegacyDynamicAssetsExample#4]
The example project of install-time asset packs can be simplified.
- It does not require PlayCoreHelperBinding

## Extra info

If you have a prebuilt asset pack (like I did; I compiled it on WSL), you can include it in your project by adding this to your Xamarin.Android project file XML after all other item groups:

```
  <ItemGroup>
    <AndroidAppBundleModules Include="C:\assetpacks\assets.zip" />
  </ItemGroup>
```
where C:\assetpacks\assets.zip is the path to your asset pack.

You do not need the DynamicFeature.targets file in this case nor do you need the AssetsFeature project.

If someone wants to know how to build an asset pack using Windows Subsystem for Linux (WSL), he/she can check my tooling in [this zip](https://drive.google.com/file/d/1sbQ1jdZTWPiliDJK4osPfpEc8XTVLu6c/view?usp=sharing).

**Comment by dellis1972** [comment]
I'll update the example when I get back from the holidays

**Comment by dellis1972** [comment]
The `PlayCoreHelperBinding` project is no longer required for any project as I included the helpers in the official `Xamarin.Google.Android.Play.Core` 1.10.2.3 NuGet Package. As a result I have completely removed the code. 

I also updated the InstallTime example to remove the unused `using` clauses to simplify it a bit.
